### PR TITLE
Create main controller

### PR DESCRIPTION
**Pull request by kntiller**
Basic start up of Freeshelf for Goal 1.

### CODE REVIEW

**Review by amygori — COMMENTED** [review]
I want to start with pasting in the goal to give us a North Star. :star:

### Goal 1: books
Your first goal should be creating a Book model and showing an index of all books. Some details:
- Books have, at a minimum, a title, author, description, URL, and date added to the database.
- Book URLs should be unique.
- Admins can add, edit, and delete books.
- You should have initial data for books (only a few books are necessary, but it's up to you how many you seed).
- Books should be in order with the most recently added at the top.

Great! You only need to meet these specific requirements, and no others. So, you don't need styling yet, and you don't even need more than one model. You also don't need a main or homepage that is different from the books index. This makes the first job much easier! 🙌 

You are thinking ahead to add these other things, and that is good! On the other hand, t's important not to build things that you don't strictly need. Partly this is about scoping a project, and drawing strict boundaries to do that. It is also partly thoroughly understanding the product requirements and not building things you aren't being asked to build. I think your task will be much easier if you discard the things you don't need right now. 

You can leave out Author and Category for the time being. Initial requirements say that a book has an author, but we don't have any Author requirements yet. It's great that you are thinking big picture, and it's fine that you have these models now, but when it comes to meeting the goal, less complicated is better. You want to make your job as straightforward and doable as possible. There isn't anything in the requirements that can't be met if you just treat author as an attribute on book for now -- just pointing that out as a general principle. You can keep the models; I'd say just ignore them until you have the app working.

I also suggest changing the `root` route to point to books#index and ignoring main for now. And styling always comes last (sad but true most of the time, unless you are working with styled React components...one day...). It doesn't hurt to have it in the back of your mind, but the barebones structure and functionality is so much more important.

So if we a building a CRUD app for Books, and we already have a Book model, that means a good place to focus is the controller. If you run your rails app and go to your `/books` route, your server will tell you what you need to build next. Just do one thing at a time, and only that one thing, before you move on to writing code for something else. Get that action working, maybe seed the database (let me know if I can help you do this -- it is a quick thing) with a book or two so you can see it working, and then once that looks good, move on to the next action. 

This is a good place to mention that you can use controller tests to guide you with this! It looks like you got the test files courtesy of `rails generate` when you made the controller. You can look back at other Rails apps you made in your tutorials to see what the basic controller tests for CRUD actions look like as a guide. I'm not a huge proponent of TDD but sometimes writing tests beforehand helps to clarify what you are building and gives you a structure to work off of.

The process is always an iterative one, as you know, so don't worry about getting everything in place simultaneously. One little thing working at at a time is the way forward. I forget where this saying comes from, but the order of operations for the development process is described as "Make it work; make it right; make it fast." We don't always get to all three of those steps, of course. 😛 

This is a really hard flow to spontaneously generate on your own the first time without a tutorial! You are always welcome to ask any one of us (I feel sure I can speak for our teammates on this point) to sit with you and work through it, whether in the office or remotely. Let me know if I can clarify anything or if I didn't address something you wanted feedback about! :all_the_parrots:

Do you want to merge this in so you can keep going? What do you think?

**Comment by kntiller** [comment]
> Do you want to merge this in so you can keep going? What do you think?

Thank you very much for the feedback! I think it was very insightful to see how much more I was adding then just the task so that was very helpful. With that said, I did find myself in a blocker where I believe I created the other models a little differently then I would like, so I feel like moving forward with just the parts associated to the task would be best. So with that said, may I ask what is the general best practice? Would it be to revert certain commits that can get me back to the point of just this particular goal?

**Comment by amygori** [comment]
Yay! I think you have a choice (as always, and as usual it involves weighing considerations). 

Since this branch is called `create-main-controller`, you could consider whether it represents accurately the change you want to introduce. If not, you might abandon this branch and create a new one, either off of master or even off of this branch. What you want to think about is this: how much work would it be to start over at master vs. continuing with this same history?

If you need to revert more than one commit, you might have a case for starting over. There are ways to rewrite history to drop or preserve commits when you are trying to salvage a branch or start a new one with only select work. If you are up for git adventures I could show you how to do that, although these things are generally not great adventures for beginners because they can sometimes lead to more harm than good. Still, totally happy to show you how to!

**Comment by kntiller** [comment]
> If you need to revert more than one commit, you might have a case for starting over. There are ways to rewrite history to drop or preserve commits when you are trying to salvage a branch or start a new one with only select work. If you are up for git adventures I could show you how to do that, although these things are generally not great adventures for beginners because they can sometimes lead to more harm than good. Still, totally happy to show you how to!


I like the idea of starting a new branch! I did not even think of that. I am glad we did this because now that opens up for me that until is it merged, it is not "permanent." I don't know how but I had it stuck in my head that I was kind of married to this code and that working through each commit would be the best course of action.

After seeing it that way, since this is so new and I really did not complete Goal 1 because I did go "all over the place," I would like a to have a new go at it. 

As far as the Git adventures. I think it would be best for me to stick to one thing and then go from there. I am finding that my brain is bouncing all over the place and your feedback only supported it more. I would like to work on Goal 1 and then as this progresses maybe getting introduced to new Git concepts and utilizing them to work through blockers and code changes.

Would it be possible to get a list of commands from you that might be good to incorporate through this process so I can mark them off when I feel that I understand them? Is that a reasonable idea?

**Pull request closed without merging**
